### ISSUE TITLE
Missing DLL

### ISSUE THREAD

**Issue by ckgio99** [nomi-san/aram-booster#1]
Mình bị lỗi như trong ảnh, làm các kiểu rồi vẫn chưa fix được :(
Mình dùng windows 7 64 bit

https://ibb.co/gjb09Hc

**Comment by nomi-san** [comment]
Mình đoán là bạn sử dụng **curl** trong file zip, nó được lấy từ Windows 10 nên khi chạy trên Windows 7 sẽ bị thiếu dll.
Hiện tại thì không có bản **curl** nào tương tự dành cho Windows 7, nên bạn có thể sử dụng các implementation khác.

Trong mục release cũng đã có build sẵn file exe của nodejs.

**Comment by nomi-san** [comment]
Mình đã update bản curl mới, hỗ trợ hầu hết các bản Windows. Chỉ cần giải nén **curl.exe** trong **curl.zip** và copy bỏ vào **C:\Windows\System32**.
