### ISSUE TITLE
It does not work anymore!

### ISSUE THREAD

**Issue by tamhac2001** [nomi-san/aram-booster#2]
Thank you very much for your work! But unfortunately from today morning it does not work anymore althought It worked fine yesterday! Can you please try to fix it!
Thank you so much!
![Untitled](https://user-images.githubusercontent.com/58587966/119093235-a7707780-ba39-11eb-9dbe-3bb475658b4d.png)

**Comment by nomi-san** [comment]
Yesterday, a hotfix is applied, but it did not affect to our program.
The nodejs built has been deprecated, please try Batch version.

**Comment by tamhac2001** [comment]
I know what the problem is!!!
Somehow there is unknow change in my PATH setting so it does not work!
I add %SystemRoot%\System32\Wbem into my PATH and it work fine again!
Both batch and nodejs version work!!!
Thank you so much <3

**Comment by thang510023** [comment]
Can't use it today,  can you please try to fix it!
Thank you so much!

**Comment by nomi-san** [comment]
Yeb!
But, have you tried on other servers?
