### ISSUE TITLE
Hello, does aram boost work on the garena server? I want to buy

### ISSUE THREAD

**Issue by iammissblue** [nomi-san/aram-booster#3]
😆

**Comment by nomi-san** [comment]
It works fine on Garena, but you need RP to boost 🤣

**Comment by iammissblue** [comment]
> 它在 Garena 上运行良好，但您需要 RP 来提升 🤣

My discord QWQ#7747

**Comment by nomi-san** [comment]
I mean, It's free literally on Riot's servers, but Garena isn't.
